<?php
return array (
  'app' => 'Admin',
  'model' => 'Setting',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '系统维护',
  'icon' => 'cogs',
  'remark' => '',
  'listorder' => '8',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'userdefault',
      'data' => '',
      'type' => '0',
      'status' => '0',
      'name' => '个人信息',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Setting',
          'action' => 'password',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '修改密码',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Setting',
              'action' => 'password_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交修改',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'site',
      'data' => '',
      'type' => '0',
      'status' => '0',
      'name' => '网站信息',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Setting',
          'action' => 'site_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '提交修改',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Route',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '路由列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Route',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '路由添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Route',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '路由添加提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Route',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '路由编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Route',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '路由编辑提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Route',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '路由删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Route',
          'action' => 'ban',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '路由禁止',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Route',
          'action' => 'open',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '路由启用',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Route',
          'action' => 'listorders',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '路由排序',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Mailer',
      'action' => 'default',
      'data' => '',
      'type' => '0',
      'status' => '0',
      'name' => '邮箱配置',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Mailer',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => 'SMTP配置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Mailer',
              'action' => 'index_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交配置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Mailer',
          'action' => 'active',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '邮件模板',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Mailer',
              'action' => 'active_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交模板',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Rbac',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '角色管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'member',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '成员管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'authorize',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '权限设置',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Rbac',
              'action' => 'authorize_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交设置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'roleedit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑角色',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Rbac',
              'action' => 'roleedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'roledelete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除角色',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'roleadd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加角色',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Rbac',
              'action' => 'roleadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'User',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '管理员',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'ban',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '禁用管理员',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'cancelban',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '启用管理员',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除管理员',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '管理员编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'User',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '管理员添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'User',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'game',
      'data' => '',
      'type' => '0',
      'status' => '0',
      'name' => '互动游戏',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'clearcache',
      'data' => '',
      'type' => '0',
      'status' => '0',
      'name' => '清除缓存',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Log',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '系统操作日志',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
  ),
);